// <auto-generated>
// Code generated by LUISGen how happy luis model.json -cs AspNetCore_EchoBot_With_State.HowHappyLUISModel -o 
// Tool github: https://github.com/microsoft/botbuilder-tools
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
using Newtonsoft.Json;
using System.Collections.Generic;
namespace AspNetCore_EchoBot_With_State
{
    public class HowHappyLUISModel: Microsoft.Bot.Builder.Core.Extensions.IRecognizerConvert
    {
        public string Text;
        public string AlteredText;
        public enum Intent {
            LeastEmotional, 
            MostEmotional, 
            None, 
            SortedByEmotion, 
            SpecificPosition
        };
        public Dictionary<Intent, Microsoft.Bot.Builder.Ai.LUIS.IntentData> Intents;

        public class _Entities
        {
            // Simple entities
            public string[] emotion;
            public string[] anger;
            public string[] contempt;
            public string[] disgust;
            public string[] fear;
            public string[] happiness;
            public string[] neutral;
            public string[] sadness;
            public string[] surprise;

            // Built-in entities
            public double[] ordinal;

            // Instance
            public class _Instance
            {
                public Microsoft.Bot.Builder.Ai.LUIS.InstanceData[] emotion;
                public Microsoft.Bot.Builder.Ai.LUIS.InstanceData[] anger;
                public Microsoft.Bot.Builder.Ai.LUIS.InstanceData[] contempt;
                public Microsoft.Bot.Builder.Ai.LUIS.InstanceData[] disgust;
                public Microsoft.Bot.Builder.Ai.LUIS.InstanceData[] fear;
                public Microsoft.Bot.Builder.Ai.LUIS.InstanceData[] happiness;
                public Microsoft.Bot.Builder.Ai.LUIS.InstanceData[] neutral;
                public Microsoft.Bot.Builder.Ai.LUIS.InstanceData[] sadness;
                public Microsoft.Bot.Builder.Ai.LUIS.InstanceData[] surprise;
                public Microsoft.Bot.Builder.Ai.LUIS.InstanceData[] ordinal;
            }
            [JsonProperty("$instance")]
            public _Instance _instance;
        }
        public _Entities Entities;

        [JsonExtensionData(ReadData = true, WriteData = true)]
        public IDictionary<string, object> Properties {get; set; }

        public void Convert(dynamic result)
        {
            var app = JsonConvert.DeserializeObject<HowHappyLUISModel>(JsonConvert.SerializeObject(result));
            Text = app.Text;
            AlteredText = app.AlteredText;
            Intents = app.Intents;
            Entities = app.Entities;
            Properties = app.Properties;
        }

        public (Intent intent, double score) TopIntent()
        {
            Intent maxIntent = Intent.None;
            var max = 0.0;
            foreach (var entry in Intents)
            {
                if (entry.Value.Score > max)
                {
                    maxIntent = entry.Key;
                    max = entry.Value.Score;
                }
            }
            return (maxIntent, max);
        }
    }
}
