/**
* <auto-generated>
* Code generated by LUISGen BankoLuisModel.json -ts BankoLuisModel -o 
* Tool github: https://github.com/microsoft/botbuilder-tools
* Changes may cause incorrect behavior and will be lost if the code is
* regenerated.
* </auto-generated>
*/ 
import {DateTimeSpec, IntentData, InstanceData, NumberWithUnits} from 'botbuilder-ai';

export interface _Intents { 
    Balance: IntentData;
    None: IntentData;
    Transfer: IntentData;
};

export interface _Instance {
    AccountLabel?: InstanceData[];
    Payee?: InstanceData[];
    datetime?: InstanceData[];
    money?: InstanceData[];
}

export interface _Entities {
    // Simple entities
    AccountLabel?: string[];
    Payee?: string[];

    // Built-in entities
    datetime?: DateTimeSpec[];
    money?: NumberWithUnits[];
    $instance : _Instance;
}

export interface BankoLuisModel {
    text: string;
    alteredText?: string;
    intents: _Intents;
    entities: _Entities;
    [propName: string]: any;
}
